name: "e-face"
description: "Personalized user interface add-on (testing)"
version: "b0.1.3"
slug: "eface"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
ports:
  "8000/tcp": 8000
  "443/tcp": null
webui: "http://[HOST]:[PORT:8000]"
options:
  https_enabled: false
  https_domain: ""
  https_email: ""
schema:
  https_enabled: bool
  https_domain: str?
  https_email: str?
